#!/usr/bin/env bash
# task0

if [ $# == 1 ]; then
	DOMAIN="$1"

	for subdom in "www" "lb-01" "web-01" "web-02"
	do
		X="${subdom}.${DOMAIN}"
		RECORD=$(dig "$X" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
		IP=$(dig "$X" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
		echo "The subdomain $subdom is a $RECORD record and points to $IP"
	done
else
	DOMAIN="$1"
	SUBDOMAIN="$2"
	X="${SUBDOMAIN}.${DOMAIN}"
	RECORD=$(dig "$X" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	IP=$(dig "$X" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo "The subdomain $SUBDOMAIN is a $RECORD record and points to $IP"
fi
