#!/usr/bin/env bash
# 1. Install nginx web server
sudo apt-get update
sudo apt-get install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
