#!/usr/bin/env bash
# 1. Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i "/# pass the PHP/i location /redirect_me {\n     rewrite ^/redirect_me(.*)$ https://ciudadseva.com/texto/extasis/$1 permanent; \n}" /etc/nginx/sites-available/default
sudo service nginx start
