#!/usr/bin/env bash
# 0. Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx

sudo chown -R ubuntu /var/www/html/
sudo chmod 755 /var/www/html/
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
# Permissions
sudo chown -R ubuntu /etc/nginx
sudo chmod 755 /etc/nginx/
# Install nginx web server
sudo sed -i "/server_name _;/a location /redirect_me {\n     rewrite ^/redirect_me(.*)$ https://ciudadseva.com/texto/extasis/ permanent; \n}" /etc/nginx/sites-available/default

# custom 404 page that contains the string Ceci n'est pas une page.
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sed -i "/listen 80 default_server;/a add_header X-Served-By ${HOSTNAME};" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
