#!/usr/bin/env bash
# 1. Install your load balancer 
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo chown -R ubuntu /etc/default/
sudo chmod 755 /etc/default/
echo -e "ENABLED=1" >> /etc/default/haproxy
sudo chown -R ubuntu /etc/haproxy/
sudo chmod 755 /etc/haproxy/
echo -e "frontend http_front\n\tbind *:80\n\tdefalut_back http_back" >> /etc/haproxy/haproxy.cfg
echo -e "backend http_back\n\tbalance roundrobin\n\tserver 2762-web-01 34.138.182.242:80\n\tserver 2762-web-02 54.89.68.173:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
