#!/usr/bin/env bash
# 0. Nginx likes port 80
sudo sed -i 's/ ipv6only=on//g' /etc/nginx/sites_available/default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/ ipv6only=on//g' /etc/nginx/sites-enabled/default
sudo service nginx restart
