#!/usr/bin/env bash
# 0. Nginx likes port 80
sudo sed -i 's/listen [::]:80 default_server ipv6only=on;/listen [::]:80 default_server;/g' /etc/nginx/sites_available/default
sudo sed -i 's/listen 8080 default_server ;/listen 80 default_server;/g' /etc/nginx/sites_enabled /default
sudo sed -i 's/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server;/g' /etc/nginx/sites_enabled /default
sudo service nginx restart
