#!/usr/bin/env bash
# displays the content of the file /etc/passwd

file=/etc/passwd

while IFS=: read -r user pwsd uid gid info home shell;
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pwsd, more info about the user here: $info"
done < $file

